version: '2'

services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  feedbackapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

